### ISSUE TITLE
Moving a Collider into another doesn't create `Proximity` or `Contact` Events.

### ISSUE THREAD

**Issue by jojolepro** [rustsim/nphysics#168] opened 2019-01-03 15:10 UTC
I'm creating the following:
Ground: 1 convex mesh collider
Player: 1 ball collider (contact) + rigid body
PlayerSensor: 1 ball collider (sensor)

Each frame, I'm moving the sensor to the position of the player collider with an offset. (ie playersensor = player + Vector(0, -0.4, 0)

When I move the player around, it does what I expect. It collides with the ground, and generates Contact events.

However, the PlayerSensor does not generate any Contact events (expected) or any Proximity events (not expected) with the Ground collider.

Interaction between Player and PlayerSensor is disabled.

What I expect: Proximity events to be emitted when the sensor collider is manually moved.

**Comment by sebcrozet** [comment] 2019-02-09 15:52
@jojolepro Please attempt to reproduce this bug with the latest version of nphysics (0.10) and with a non-modified version of ncollide (as far as I know you are using your own fork that includes deep modifications of the contact groups system).

**Comment by sebcrozet** [comment] 2019-03-02 12:52
I'm closing this because, after discussing this on Discord, we found out this was am issue with nphysics-ecs-dumb that performed several timestep without giving you a chance of handling events for each of those timesteps.

Please reopen if you experience this problem again without this nphysics-ecs-dumb limitation.

**Closed by sebcrozet** 2019-03-02 12:52 UTC

**Comment by jojolepro** [comment] 2019-03-02 16:32
No that is still a thing however. Its when you manually change the collider position, instead of using a rigid body's velocity to move it.
